term xterm-256color

hide_window_decorations no

font_family      Inconsolata
font_size 17.0

#font_family      Consolas
#font_size 14.0
#modify_font baseline -2

#bold_font        Berkeley Mono Bold
#italic_font      Berkeley Mono Italic
#bold_italic_font Berkeley Mono Bold Italic

cursor_blink_interval 0
shell_integration disabled

confirm_os_window_close 0

placement_strategy top-left
window_padding_width 0

# don't allow shared clipboard with operating system
clipboard_control read-clipboard-ask read-primary-ask
